### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tjohn123456**
updated the readme file.

### CODE REVIEW

**Comment by cloudguy2014** [comment]
@tans-org/explorer-team I am on it.

**Comment by simplyjoe13** [comment]
@cloudguy2014 how is the progress going?

**Comment by simplyjoe13** [comment]
@simplyjoe13 can you review the code?

**Comment by cloudguy2014** [comment]
@simplyjoe13 can you review my changes? Thx

**Comment by simplyjoe13** [comment]
@tans-org/explorer-team can yo all prioritize resolving this?

**Comment by tjohn123456** [comment]
@tans-org/explorer-team can you all fix this soon?

**Pull request merged**
